WITH CTE AS (
select
TO_TIMESTAMP(STARTED_AT,'MM/DD/YYYY HH24:MI:SS') AS STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT,'MM/DD/YYYY HH24:MI:SS')) AS DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT,'MM/DD/YYYY HH24:MI:SS')) AS HOUR_STARTED_AT,
{{ day_type('STARTED_AT') }} AS DAY_TYPE,
{{ get_season('STARTED_AT') }}  AS STATION_OF_YEAR
from
{{ source('demo', 'bike') }}
where TRY_TO_TIMESTAMP(STARTED_AT,'MM/DD/YYYY HH24:MI:SS') IS NOT NULL
)
select 
*
from CTE


