WITH TRIPS AS (
    select 
        RIDE_ID,
        DATE(STARTED_AT) AS TRIP_DATE,
        START_STATIO_ID AS START_STATION_ID,
        END_STATION_ID,
        MEMBER_CSUAL AS MEMBER_CASUAL,
        TIMESTAMPDIFF(SECOND,STARTED_AT,ENDED_AT) AS TRIP_DURATION_SECONDS  
    from {{ ref('stg_bike') }}
    --where TRY_TO_TIMESTAMP(STARTED_AT,'MM/DD/YYYY HH24:MI:SS') IS NOT NULL
)
select * from TRIPS